#!/usr/bin/env python3
"""
HivePulse house style, drawn from scratch.

The contest covers set the visual language: a deep navy ground, a warm gold bloom,
a mosaic of tumbling gold tiles, dimensional gold display type, and the real crimson
and purple HivePulse badge. This module reproduces that language in code.

Nothing here is generated by a model. That is deliberate:

  * no invisible provenance watermark of any kind
  * free to re-render, so a card carrying a live number costs nothing to update
  * the gold is our gold and the logo is our logo, every time, not an approximation

Import it; do not run it.
"""

from PIL import Image, ImageDraw, ImageFilter, ImageFont
import numpy as np
import os
import random

# ---- palette, sampled from the contest covers and the logo file ---------------

NAVY_DEEP = (8, 14, 30)
NAVY      = (16, 26, 51)
GOLD_HI   = (255, 226, 138)
GOLD      = (247, 181, 41)
GOLD_LO   = (198, 124, 18)
EMBER     = (120, 62, 12)
CRIMSON   = (227, 30, 60)
PLUM      = (45, 27, 78)
INK       = (255, 255, 255)
INK_2     = (206, 216, 232)
INK_3     = (140, 155, 178)
EMERALD   = (52, 211, 153)

LOGO = 'HivePulse3-Transparent.png'

_F = {'bold': ['C:/Windows/Fonts/segoeuib.ttf', 'C:/Windows/Fonts/arialbd.ttf'],
      'semi': ['C:/Windows/Fonts/seguisb.ttf', 'C:/Windows/Fonts/segoeuib.ttf'],
      'reg':  ['C:/Windows/Fonts/segoeui.ttf', 'C:/Windows/Fonts/arial.ttf']}
_cache = {}


def font(weight, size):
    key = (weight, size)
    if key not in _cache:
        for path in _F[weight]:
            if os.path.exists(path):
                _cache[key] = ImageFont.truetype(path, size)
                break
        else:
            _cache[key] = ImageFont.load_default()
    return _cache[key]


# ---- ground ------------------------------------------------------------------

def _radial(size, cx, cy, radius, inner, outer):
    """Radial gradient, built at an eighth scale and upsampled -- smooth and cheap."""
    w, h = size
    sw, sh = max(1, w // 8), max(1, h // 8)
    g = Image.new('RGB', (sw, sh))
    px = g.load()
    for y in range(sh):
        for x in range(sw):
            dx = (x / sw - cx) * w
            dy = (y / sh - cy) * h
            t = min(1.0, ((dx * dx + dy * dy) ** .5) / radius)
            t = t ** 0.85
            px[x, y] = tuple(round(inner[i] + (outer[i] - inner[i]) * t) for i in range(3))
    return g.resize((w, h), Image.BICUBIC)


def gold_ground(w, h, bloom=(0.74, 0.46), intensity=1.0, seed=5, mosaic=1.0):
    """Navy field with a warm gold bloom and a mosaic of tumbling tiles.

    The bloom sits right of centre by default, which keeps the left of the frame
    calm enough for a left-aligned text column.

    `mosaic` scales tile density. Promotional cards want the full 1.0 -- the tumbling
    tiles are half of what makes a card read as HivePulse. Data charts want 0.0: a
    tile behind a 6px dot is indistinguishable from a data point, and legibility beats
    brand energy on anything a reader has to actually parse.
    """
    base = _radial((w, h), bloom[0], bloom[1], w * 0.78,
                   (round(88 * intensity) + 18, round(52 * intensity) + 14, 22),
                   NAVY_DEEP)
    core = _radial((w, h), bloom[0], bloom[1], w * 0.34,
                   (round(190 * intensity), round(126 * intensity), 34), (0, 0, 0))
    im = Image.blend(base, Image.new('RGB', (w, h), NAVY), 0.28)
    im = Image.fromarray(
        np.clip(np.asarray(im, dtype=np.int16) + np.asarray(core, dtype=np.int16),
                0, 255).astype(np.uint8))

    # mosaic: tumbling squares, denser and brighter toward the bloom
    rnd = random.Random(seed)
    tiles = Image.new('RGBA', (w, h), (0, 0, 0, 0))
    td = ImageDraw.Draw(tiles)
    for _ in range(int(340 * mosaic)):
        x = rnd.uniform(-0.05, 1.05) * w
        y = rnd.uniform(-0.05, 1.05) * h
        d = ((x / w - bloom[0]) ** 2 + (y / h - bloom[1]) ** 2) ** .5
        if rnd.random() > max(0.06, 1.15 - d * 1.9):
            continue
        s = rnd.uniform(7, 30) * (1.25 - min(1.0, d))
        a = int(max(0, 210 * (1.05 - d * 1.35)) * intensity)
        col = GOLD_HI if rnd.random() < 0.30 else (GOLD if rnd.random() < 0.6 else GOLD_LO)
        box = Image.new('RGBA', (int(s * 2) + 4, int(s * 2) + 4), (0, 0, 0, 0))
        ImageDraw.Draw(box).rectangle([2, 2, s + 2, s + 2], fill=col + (a,))
        box = box.rotate(rnd.uniform(0, 90), resample=Image.BICUBIC, expand=False)
        tiles.alpha_composite(box, (int(x), int(y)))
    td = None
    glow = tiles.filter(ImageFilter.GaussianBlur(9))
    im = Image.alpha_composite(im.convert('RGBA'), glow)
    im = Image.alpha_composite(im, tiles).convert('RGB')

    # scrim so the left column always clears contrast, whatever the bloom does
    scrim = Image.new('L', (w, 1))
    for x in range(w):
        t = x / w
        scrim.putpixel((x, 0), int(178 * (1 - t) ** 1.5))
    return Image.composite(Image.new('RGB', (w, h), NAVY_DEEP), im,
                           scrim.resize((w, h)))


# ---- dimensional gold type ---------------------------------------------------

def gold_text(im, xy, text, fnt, anchor='la', stroke=4,
              top=GOLD_HI, mid=GOLD, bot=GOLD_LO):
    """Draw text filled with a vertical gold gradient over a dark stroke.

    The stroke is what makes the cover type read at thumbnail size; without it gold
    on gold disappears. Returns the drawn width.
    """
    d = ImageDraw.Draw(im)
    box = d.textbbox(xy, text, font=fnt, anchor=anchor, stroke_width=stroke)
    # callers pass float centres; the mask and paste offsets must be whole pixels
    x0, y0, x1, y1 = (int(v) for v in box)
    w, h = max(1, x1 - x0), max(1, y1 - y0)

    mask = Image.new('L', (w, h), 0)
    ImageDraw.Draw(mask).text((xy[0] - x0, xy[1] - y0), text, font=fnt,
                              anchor=anchor, fill=255)

    grad = Image.new('RGB', (1, h))
    gp = grad.load()
    for y in range(h):
        t = y / max(1, h - 1)
        a, b = (top, mid) if t < 0.55 else (mid, bot)
        tt = t / 0.55 if t < 0.55 else (t - 0.55) / 0.45
        gp[0, y] = tuple(round(a[i] + (b[i] - a[i]) * tt) for i in range(3))
    grad = grad.resize((w, h))

    if stroke:
        d.text(xy, text, font=fnt, anchor=anchor, fill=(26, 14, 34),
               stroke_width=stroke, stroke_fill=(26, 14, 34))
    im.paste(grad, (x0, y0), mask)
    return x1 - x0


def badge(im, x, y, d=76, ring=True):
    """The real HivePulse mark on a white chip.

    The source art is a light-background lockup -- crimson ring, purple pulse line,
    wordmark underneath. On a dark card the mark vanishes, so it is cropped to the
    circular emblem and set on white, which is what it was drawn for.
    """
    if not os.path.exists(LOGO):
        return x
    src = Image.open(LOGO).convert('RGBA')
    s = src.width / 1024.0
    mark = src.crop((int(225 * s), int(135 * s), int(805 * s), int(715 * s)))
    chip = Image.new('RGBA', (d, d), (0, 0, 0, 0))
    cd = ImageDraw.Draw(chip)
    cd.ellipse([0, 0, d - 1, d - 1], fill=(255, 255, 255, 255))
    if ring:
        cd.ellipse([0, 0, d - 1, d - 1], outline=GOLD + (255,), width=max(2, d // 26))
    inner = int(d * 0.80)
    m = mark.resize((inner, inner), Image.LANCZOS)
    off = (d - inner) // 2
    chip.paste(m, (off, off), m)
    im.paste(chip, (x, y), chip)
    return x + d


def wordmark(im, x, y, size=34):
    """'HivePulse · @HdevCore' footer lockup, gold name and muted handle."""
    d = ImageDraw.Draw(im)
    f = font('bold', size)
    gold_text(im, (x, y), 'HivePulse', f, stroke=3)
    w = d.textlength('HivePulse', font=f)
    d.text((x + w + 18, y + size * 0.12), '·  @HdevCore',
           font=font('semi', round(size * 0.82)), fill=INK_3)
